# http://blog.trk.in.rs/2015/12/01/vim-tips/
# ~/.rubocop.yml is used when there is no local .rubocop.yml
AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - config/unicorn.rb
    - db/schema.rb
    - /home/orlovic/.rvm/**/*
    - node_modules/**/*
    - db/migrate/*

# 'class ActionDispatch::IntegrationTest' in single line, no need two lines
Style/ClassAndModuleChildren:
  Enabled: false

# it is OK that code explains instead class documentation
Style/Documentation:
  Enabled: false

# config, tasks and test for setup data could be very long
Metrics/BlockLength:
  Exclude:
    - 'lib/**/*'
    - 'test/**/*'
    - 'config/**/*'

# big test big ABC size
Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'test/**/*'

# line length is not important in db and tests
Metrics/LineLength:
  Max: 125
  Exclude:
    - 'db/**/*'
    - 'test/**/*'
    - 'spec/**/*'

# put comma after each line [1,]
Style/TrailingCommaInArrayLiteral:
  Enabled: false

# put comma after each line {a:1,}
Style/TrailingCommaInHashLiteral:
  Enabled: false

# also in arguments
Style/TrailingCommaInArguments:
  Enabled: false

# methods in 10 lines are OK but some are bigger
Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'lib/**/*'
    - 'test/**/*'

# classes could be huge in tests
Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

# do not need to write # frozen_string_literal: true
Style/FrozenStringLiteralComment:
  Enabled: false

Rails:
  Enabled: true

Rails/FilePath:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

# errors.add(:base, 'Failed') and return false # no need to use &&
Style/AndOr:
  Enabled: false

# assert_match /regexp/, response.body # no need for parenthesis
Lint/AmbiguousRegexpLiteral:
  Enabled: false
