# http://blog.trk.in.rs/2015/12/01/vim-tips/
AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - config/unicorn.rb
    - db/schema.rb
    - /home/orlovic/.rvm/**/*
    - node_modules/**/*
    - db/migrate/*

Rails:
  Enabled: true

# [1,]
Style/TrailingCommaInLiteral:
  Enabled: false

Rails/Output:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

# Style/Documentation:
#   Enabled: false
# 
# Style/TrailingCommaInArguments:
#   Enabled: false
# 
# 
# Style/FileName:
#   Enabled: false
# 
# 
# 
# Metrics/AbcSize:
#   Max: 40 # default was 15
# 
# Metrics/MethodLength:
#   Max: 20 # default was 10
# 
# Metrics/LineLength:
#   Max: 115 # default was 80
# 
# Metrics/ClassLength:
#   Max: 120 # default was 100
